AptCoderTask/AptCoderTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

AptCoderTask/accounts/urls.py
from django.urls import path
from accounts.views import login_view, SignUpView, StudentSignUpView, TeacherSignUpView, logout_view, teacher_profile, student_profile

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/student/',
         StudentSignUpView.as_view(), name='student_signup'),
    path('signup/teacher/',
         TeacherSignUpView.as_view(), name='teacher_signup'),
    path('logout/', logout_view, name='logout'),
    path('teacher/profile/', teacher_profile, name='teacher_profile'),
    path('student/profile/', student_profile, name='student_profile'),
]

AptCoderTask/core/urls.py
from django.urls import path
from core.views import HomeView, course_list, EnrolledCourseDetailView, CourseDetailView, add_course, CourseListView, StudentDetailView, TeacherDetailView, StudentEnrollCourseView, StudentCourseListView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('add/course/', add_course, name='add_course'),
    path('<slug:slug>/details/', CourseDetailView.as_view(), name='course_detail'),
    path('enrolled/<slug:slug>/details/', EnrolledCourseDetailView.as_view(), name='enrolled_course_detail'),
    path('list/', course_list, name='course_list'),
    path('courses/list/', CourseListView.as_view(), name='courses'),
    path('enroll-course/', StudentEnrollCourseView.as_view(),
         name='student_enroll_course'),
    path('enroll/courses/', StudentCourseListView.as_view(),
         name='student_enroll_courses'),
    path('<slug:slug>/student/details/',
         StudentDetailView.as_view(), name='student_detail'),
    path('<slug:slug>/teacher/details/',
         TeacherDetailView.as_view(), name='teacher_detail'),

]

AptCoderTask/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{% block head_title %}{% endblock head_title %}</title>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">

  <style>
    main {
        padding-top: 3rem;
        padding-bottom: 2rem;
    }
    .extra-margins {
        margin-top: 1rem;
        margin-bottom: 2.5rem;
    }
    .jumbotron {
        text-align: center;
    }
    .navbar {
        background-color: #3b295a;
    }
    footer.page-footer {
        background-color: #3b295a;
        margin-top: 2rem;
    }
  {% block custom_css %}
  {% endblock custom_css %}
  </style>
</head>
<body>  
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Apt Coder</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'core:courses' %}">Courses</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
              {% if user.is_teacher %}
              <a class="nav-link" href="{% url 'core:course_list' %}">DASHBOARD</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:teacher_profile' %}">{{ user.username|title}}</a>
              {% else %}
              {% if user.is_student %}
              <a class="nav-link" href="{% url 'accounts:student_profile' %}">{{ user.username|title}}</a>
              {% endif %}
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:student_enroll_courses' %}">Enrolled Courses</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              </li>
            </ul>
        {% else %}
          <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                </li>
            </ul>
        {% endif %}
        </div>
      </div>
  </nav>
</header>
  {% block content %}
  {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endblock content %}
  {% comment %} {% include 'footer.html' %}   {% endcomment %}
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>

</html>

AptCoderTask/templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small pt-4">
  <!-- Footer Links -->
  <div class="container text-center text-md-left">
    <!-- Grid row -->
    <div class="row">
      <!-- Grid column -->
      <div class="col-md-4 mx-auto">
        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>
      </div>
      <!-- Grid column -->
      <hr class="clearfix w-100 d-md-none">
      <!-- Grid column -->
      <div class="col-md-2 mx-auto">
        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->
      <hr class="clearfix w-100 d-md-none">
      <!-- Grid column -->
      <div class="col-md-2 mx-auto">
        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
      <hr class="clearfix w-100 d-md-none">
      <!-- Grid column -->
      <div class="col-md-2 mx-auto">
        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->
  <hr>
  <!-- Call to action -->
  <ul class="list-unstyled list-inline text-center py-2">
    <li class="list-inline-item">
      <h5 class="mb-1">Register for free</h5>
    </li>
    <li class="list-inline-item">
      <a href="#!" class="btn btn-danger btn-rounded">Sign up!</a>
    </li>
  </ul>
  <!-- Call to action -->
  <hr>
  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a class="btn-floating btn-fb mx-1">
        <i class="fab fa-facebook-f"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-tw mx-1">
        <i class="fab fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-gplus mx-1">
        <i class="fab fa-google-plus-g"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-li mx-1">
        <i class="fab fa-linkedin-in"> </i>
      </a>
    </li>
  </ul>
  <!-- Social buttons -->
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->