AptCoderTask/AptCoderTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

AptCoderTask/accounts/urls.py
from django.urls import path
from accounts.views import login_view, SignUpView, StudentSignUpView, TeacherSignUpView, logout_view, teacher_profile, student_profile

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/student/',
         StudentSignUpView.as_view(), name='student_signup'),
    path('signup/teacher/',
         TeacherSignUpView.as_view(), name='teacher_signup'),
    path('logout/', logout_view, name='logout'),
    path('teacher/profile/', teacher_profile, name='teacher_profile'),
    path('student/profile/', student_profile, name='student_profile'),
]

AptCoderTask/core/urls.py
from django.urls import path
from core.views import HomeView, course_list, EnrolledCourseDetailView, CourseDetailView, add_course, CourseListView, StudentDetailView, TeacherDetailView, StudentEnrollCourseView, StudentCourseListView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('add/course/', add_course, name='add_course'),
    path('<slug:slug>/details/', CourseDetailView.as_view(), name='course_detail'),
    path('enrolled/<slug:slug>/details/', EnrolledCourseDetailView.as_view(), name='enrolled_course_detail'),
    path('list/', course_list, name='course_list'),
    path('courses/list/', CourseListView.as_view(), name='courses'),
    path('enroll-course/', StudentEnrollCourseView.as_view(),
         name='student_enroll_course'),
    path('enroll/courses/', StudentCourseListView.as_view(),
         name='student_enroll_courses'),
    path('<slug:slug>/student/details/',
         StudentDetailView.as_view(), name='student_detail'),
    path('<slug:slug>/teacher/details/',
         TeacherDetailView.as_view(), name='teacher_detail'),

]

AptCoderTask/core/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from accounts.models import User


class Courses(models.Model):
    owner = models.ForeignKey(User,
                              related_name='courses_created',
                              on_delete=models.CASCADE)
    course_name = models.CharField(max_length=250)
    description = models.TextField()
    date = models.DateField(auto_now_add=True)
    instructer = models.CharField(max_length=150, blank=True, null=True)
    students = models.ManyToManyField(User, related_name='courses_joined',
                                      blank=True)
    slug = AutoSlugField(('slug'), max_length=50,
                         unique=True, populate_from=('course_name',))

    def __str__(self):
        return self.course_name

    def get_absolute_url(self):
        pass

    class Meta:
        ordering = ['-date']

AptCoderTask/core/forms.py
from django import forms
from core.models import Courses


class CourseForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = ['owner', 'course_name', 'description', 'instructer', ]


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Courses.objects.all(),
                                    widget=forms.HiddenInput)

AptCoderTask/core/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from core.models import Courses
from core.forms import CourseForm, CourseEnrollForm


class HomeView(ListView):
    model = Courses
    template_name = 'core/index.html'


class CourseListView(ListView):
    model = Courses
    template_name = 'core/courses.html'


class CourseDetailView(DetailView):
    model = Courses
    template_name = 'core/course_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView,
                        self).get_context_data(**kwargs)
        context['enroll_form'] = CourseEnrollForm(
            initial={'course': self.object})
        return context


class EnrolledCourseDetailView(DetailView):
    model = Courses
    template_name = 'core/enrolled_course_detail.html'


@login_required(login_url='accounts:login')
def course_list(request):
    courses = Courses.objects.prefetch_related('students')
    return render(request, 'core/course_list.html', {"courses": courses})


@login_required(login_url='accounts:login')
def add_course(request):
    if request.method == 'POST':
        form = CourseForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('core:index')
    form = CourseForm()
    context = {
        'form': form
    }
    return render(request, 'core/add_course.html', context)


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super(StudentEnrollCourseView,
                     self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('core:enrolled_course_detail',
                            args=[self.course.slug])


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Courses
    template_name = 'core/enroll_courses.html'

    def get_queryset(self):
        qs = super(StudentCourseListView, self).get_queryset()
        return qs.filter(students__in=[self.request.user])


class StudentDetailView(DetailView):
    model = Courses
    template_name = 'core/student_detail.html'


class TeacherDetailView(DetailView):
    model = Courses
    template_name = 'core/teacher_detail.html'

AptCoderTask/core/templates/core/add_course.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}Add Course{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="container mt-3">
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Add Course</h2>
      <form method="post" action="{% url 'core:add_course' %}" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Add Course</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

AptCoderTask/core/templates/core/course_detail.html
{% extends 'base.html' %}
{% block head_title %}Course Details{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="container mt-5">
<h1>Course Name </h1>
{{ object.course_name}} <br>
<a href="{% url 'core:teacher_detail' object.slug %}">{{ object.instructer}}</a> <br>
{{ object.date}} <br>
{{ object.description}} <br>
    {% if user.is_student %}
        <form action="{% url "core:student_enroll_course" %}" method="post">
            {{ enroll_form }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Enroll now">
        </form>
    {% elif not user.is_teacher %}
    <a href="{% url 'accounts:login' %}">Login to Enroll</a>
    {% endif %}
</div>
{% endblock content %}

AptCoderTask/core/templates/core/course_list.html
{% extends 'base.html' %}
{% block head_title %}Course List{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="container mt-5">
<h1>Course list</h1>
    <ol>
    {% if user.is_authenticated and user.is_teacher %}
    <a href="{% url 'core:add_course' %}" class="btn btn-outline-unique" rel="nofollow">Add course</a>
        {% if courses %}
            {% for courses in courses %}
                <h3><li>{{ courses.course_name}}</li></h3>
                {% if courses.students.all %}
                <p>Students who was enrolled in this course</p>
                <ul>
                    {% for student in courses.students.all %}
                    <a href="{% url 'core:student_detail' courses.slug %}">{{ student|title }}</a>
                    {% endfor%}
                </ul>
                {% endif %}
                <a href="{% url 'core:course_detail' courses.slug %}" class="btn btn-sm" rel="nofollow">Course Details</a>
            {% endfor%}
        {% else %}
        <h3>Course not added yet.</h3>
        {% endif %}
    </ol>
    {% else %}
    <h3>Login as teacher to see this page</h3>
    {% endif %}
</div>
{% endblock content %}

AptCoderTask/core/templates/core/courses.html
{% extends 'base.html' %}
{% block head_title %}Courses{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="container mt-4">
    <h1>Course list</h1>
    {% if object_list %}
    <div class="row">
    {% for courses in object_list %}
        <div class="col-lg-4">
            <div class="card wow fadeIn" data-wow-delay="0.2s">
                <div class="card-body">
                    <h4 class="card-title">{{ courses.course_name}}</h4>
                    <p class="card-text">{{ courses.description|truncatechars:100 }}</p>
                    <a href="{% url 'core:course_detail' courses.slug %}" class="btn btn-info">Course Details</a>
                </div>
            </div>
        </div>
    {% endfor%}
    </div>
    {% else %}
    <h3>No Course</h3>
    {% endif %}
</div>


{% endblock content %}

AptCoderTask/core/templates/core/enroll_courses.html
{% extends 'base.html' %}
{% block head_title %}Enrolled Courses{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="container mt-5">
    <h1>My courses</h1>
    <div class="module">
        {% for course in object_list %}
            <div class="course-info">
                <h3>{{ course.course_name }}</h3>
                <p><a href="{% url "core:enrolled_course_detail" course.slug %}">Access contents</a></p>
            </div>
        {% empty %}
            <p>
                You are not enrolled in any courses yet.
                <a href="{% url "core:courses" %}">Browse courses</a> to enroll in a course. 
            </p>
        {% endfor %}
    </div>
{% endblock content %}

AptCoderTask/core/templates/core/enrolled_course_detail.html
{% extends 'base.html' %}
{% block head_title %}Enrolled Course Details{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="container mt-5">
<h1>Course Name </h1>
{{ object.course_name}} <br>
<a href="{% url 'core:teacher_detail' object.slug %}">{{ object.instructer}}</a> <br>
{{ object.date}} <br>
{{ object.description}} <br>
</div>
{% endblock content %}

AptCoderTask/core/templates/core/index.html
{% extends 'base.html' %}
{% block head_title %}Home{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}

<main>
    <!--Main layout-->
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.2s">
            <div class="col-md-12">
            {% if not user.is_authenticated %}
                <div class="jumbotron">
                    <h2 class="h2-responsive"></h2>
                    <br>
                    <p class="lead">
                        If you already have an account, go ahead and <a href="{% url 'accounts:login' %}">log in</a>. If you are new, get started
                        by creating a <a href="{% url 'accounts:student_signup' %}">student account</a> or a <a href="{% url 'accounts:teacher_signup' %}">teacher account</a>.
                    </p>
                    <hr>
                    <a href="{% url 'accounts:student_signup' %}" class="btn btn-outline-unique" rel="nofollow">I'm a student</a>
                    <a href="{% url 'accounts:teacher_signup' %}" class="btn btn-unique btn-ptc" rel="nofollow">I'm a teacher</a>
                </div>
                {% else %}
                {% if user.is_teacher %}
                    <h3><a href="{% url 'core:course_list' %}">Students enrolled courses</a></h3>
                {% endif %}
                {% if user.is_student %}
                <h3 class="float-left">Course list</h3>
                    <h3><a href="{% url 'core:student_enroll_courses' %}" class="float-right">Enrolled Courses</a></h3>
                {% endif %}
            {% endif %}
            </div>
        </div>
        <hr class="extra-margins">
        {% if object_list %}
        <div class="row">
        {% for courses in object_list %}
            <div class="col-lg-4">
                <div class="card wow fadeIn" data-wow-delay="0.2s">
                    <div class="card-body">
                        <h4 class="card-title">{{ courses.course_name}}</h4>
                        <p class="card-text">{{ courses.description|truncatechars:100 }}</p>
                        <a href="{% url 'core:course_detail' courses.slug %}" class="btn btn-info">Course Details</a>
                    </div>
                </div>
            </div>
        {% endfor%}
        </div>
        {% else %}
        <h3>No Course</h3>
        {% endif %}
    </div>
</main>



{% endblock content %}

AptCoderTask/core/templates/core/student_detail.html
{% extends 'base.html' %}
{% block head_title %}Student detail{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="container mt-4">

</div>


{% endblock content %}

AptCoderTask/core/templates/core/teacher_detail.html
{% extends 'base.html' %}
{% block head_title %}Teacher detail{% endblock head_title %}
{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="container mt-4">

</div>


{% endblock content %}